workflows:
    id: increments
    created_at: timestamps
    updated_at: timestamps

workflow_nodes:
    id: increments
    order: unsigned integer
    title: string
    created_at: timestamps
    updated_at: timestamps
